In [2]:
import pandas as pd
data = pd.read_csv("../data/BikeStore.csv")

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  str
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  str
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  str
 6   Customer_Gender   113036 non-null  str
 7   Country           113036 non-null  str
 8   State             113036 non-null  str
 9   Product_Category  113036 non-null  str
 10  Sub_Category      113036 non-null  str
 11  Product           113036 non-null  str
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), str(9)
memory usage: 15.5 MB

Finde die 5 ältesten Verkäufe und die 5 jüngsten Kunden

In [4]:
data.sort_values(["Date"]).head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
60993,2011-01-01,1,January,2011,42,Adults (35-64),M,United States,California,Bikes,Road Bikes,"Road-750 Black, 44",1,344,540,185,344,529
58729,2011-01-01,1,January,2011,33,Young Adults (25-34),F,France,Yveline,Bikes,Road Bikes,"Road-150 Red, 48",2,2171,3578,1097,4342,5439
58913,2011-01-01,1,January,2011,17,Youth (<25),M,Canada,British Columbia,Bikes,Road Bikes,"Road-250 Red, 44",1,1519,2443,900,1519,2419
63711,2011-01-01,1,January,2011,39,Adults (35-64),M,United States,Washington,Bikes,Road Bikes,"Road-550-W Yellow, 38",3,713,1120,482,2139,2621
49787,2011-01-01,1,January,2011,23,Youth (<25),M,Australia,Victoria,Bikes,Mountain Bikes,"Mountain-200 Black, 46",1,1252,2295,561,1252,1813

In [5]:
data.sort_values(["Customer_Age"]).head(5)

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
36307,2016-03-27,27,March,2016,17,Youth (<25),M,United States,California,Accessories,Helmets,"Sport-100 Helmet, Blue",18,13,35,383,234,617
36306,2014-03-27,27,March,2014,17,Youth (<25),M,United States,California,Accessories,Helmets,"Sport-100 Helmet, Blue",18,13,35,383,234,617
36305,2015-12-08,8,December,2015,17,Youth (<25),M,United States,California,Accessories,Helmets,"Sport-100 Helmet, Blue",28,13,35,596,364,960
36304,2013-12-08,8,December,2013,17,Youth (<25),M,United States,California,Accessories,Helmets,"Sport-100 Helmet, Blue",27,13,35,575,351,926
36303,2015-11-06,6,November,2015,17,Youth (<25),M,United States,California,Accessories,Helmets,"Sport-100 Helmet, Blue",13,13,35,277,169,446

Wie viele Frauen und Männer haben bei uns eingekauft?
- Wie viele Prozente sind das jeweils?

In [7]:
m, f = data["Customer_Gender"].value_counts()
print(data["Customer_Gender"].value_counts())
print(f"{m / len(data) * 100}%", f"{f / len(data) * 100}%")

Customer_Gender
M    58312
F    54724
Name: count, dtype: int64
51.587104993099544% 48.412895006900456%

Durchschnittliche Einkaufsmenge bei Accessories

In [36]:
data[data["Product_Category"] == "Accessories"]["Order_Quantity"].mean()

15.033685111237878

Welche Produktkategorie wird von 20-Jährigen am häufigsten gekauft?

In [44]:
data[data["Customer_Age"] == 20]["Product_Category"].value_counts()

Accessories    1414
Bikes           322
Clothing        284
Name: Product_Category, dtype: int64

Wieviele Kunden haben wir in Frankreich und Kanada gesamt?

In [23]:
c =data[data["Country"] == "Canada"].count()["Country"]
c

np.int64(14178)

In [24]:
f =data[data["Country"] == "France"].count()["Country"]
f

np.int64(10998)

In [25]:
c+f

np.int64(25176)

Gib die Anzahl der Datensätze pro Altersgruppe an

In [26]:
data.groupby(data["Age_Group"]).count()

,Date,Day,Month,Year,Customer_Age,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
Age_Group,,,,,,,,,,,,,,,,,
Adults (35-64),55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824,55824
Seniors (64+),730,730,730,730,730,730,730,730,730,730,730,730,730,730,730,730,730
Young Adults (25-34),38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654,38654
Youth (<25),17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828,17828

Welche unserer Produkte bringen im Durchschnitt den höchsten Profit ein?

In [27]:
data.groupby(data["Product"])["Profit"].mean().sort_values(ascending=False)

Product
Road-150 Red, 62           1516.774390
Road-150 Red, 52           1483.464789
Road-150 Red, 56           1446.296562
Mountain-100 Silver, 38    1429.800000
Road-150 Red, 44           1421.255981
                              ...
Touring Tire Tube            38.877364
Mountain Tire Tube           38.784478
Water Bottle - 30 oz.        38.710673
AWC Logo Cap                 17.899954
Patch Kit/8 Patches          12.123656
Name: Profit, Length: 130, dtype: float64

Finde die Stadt + Land Kombination mit dem höchsten durchschnittlichen Profit.

In [29]:
data.groupby(data["Country"] + ", " + data["State"])["Profit"].mean().sort_values(ascending=False)

United States, Arizona           1069.750000
United States, Massachusetts      776.000000
United States, Wyoming            695.625000
Canada, Alberta                   416.964286
Germany, Bayern                   404.411641
France, Essonne                   396.225352
Germany, Brandenburg              360.363636
France, Garonne (Haute)           350.706731
United States, California         346.230245
Germany, Hessen                   341.192114
France, Hauts de Seine            335.919742
Germany, Hamburg                  335.783769
United States, Florida            335.714286
United Kingdom, England           324.071439
France, Charente-Maritime         310.810811
France, Loiret                    310.185864
Australia, Queensland             310.183525
United States, Illinois           307.357143
Australia, New South Wales        300.968498
France, Seine et Marne            289.885787
France, Nord                      278.769461
France, Loir et Cher              273.008333
Australia, South Australia        271.636189
Canada, British Columbia          261.642675
Germany, Nordrhein-Westfalen      260.771739
France, Moselle                   258.227979
United States, Georgia            243.375000
France, Somme                     240.291045
United States, Oregon             238.018918
Australia, Victoria               237.371343
Australia, Tasmania               235.252762
Germany, Saarland                 228.987004
United States, Kentucky           221.600000
France, Seine (Paris)             219.573454
France, Seine Saint Denis         211.239311
France, Pas de Calais             207.911111
United States, Ohio               193.107143
United States, Montana            191.333333
France, Val d'Oise                188.431818
France, Yveline                   186.885744
United States, Washington         177.339311
France, Val de Marne              169.759494
United States, Missouri           167.666667
United States, Utah               159.500000
United States, Virginia           154.250000
United States, New York           125.100000
Canada, Ontario                    99.666667
United States, Texas               84.066667
United States, Mississippi         80.500000
United States, North Carolina      54.750000
United States, South Carolina      52.100000
United States, Minnesota           38.000000
United States, Alabama             26.250000
Name: Profit, dtype: float64